#######################################################################################
#                                                                                     #
# ██╗      ██████╗      ██╗ █████╗ ███████╗ ██████╗ ██╗   ██╗ █████╗ ██████╗ ███████╗ #
# ██║     ██╔═══██╗     ██║██╔══██╗██╔════╝██╔═══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ #
# ██║     ██║   ██║     ██║███████║███████╗██║   ██║██║   ██║███████║██████╔╝█████╗   #
# ██║     ██║   ██║██   ██║██╔══██║╚════██║██║▄▄ ██║██║   ██║██╔══██║██╔══██╗██╔══╝   #
# ███████╗╚██████╔╝╚█████╔╝██║  ██║███████║╚██████╔╝╚██████╔╝██║  ██║██║  ██║███████╗ #
# ╚══════╝ ╚═════╝  ╚════╝ ╚═╝  ╚═╝╚══════╝ ╚══▀▀═╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ #
#                                                                                     #
#######################################################################################
#
# No final do arquivo tem alguns exemplos de erros e a solução para eles.
# Além de um pequeno FAQ.
#
# VARIÁVEIS PARA ARQUIVO produtos.yml
#
# @player = Player que comprou
# @qnt    = quantidade que foi adquirida pelo player
# @grupo  = Grupo que voce configurou para o pacote no seu painel. Neste caso, VIPFerro
# @dias   = Quantidade de dias que voce configurou para o pacote no seu painel.
#
#
LojaSquare:
  # Essa opção irá imprimir uma mensagem de status para quem é op.
  # Exemplo da impressão: https://prnt.sc/smvuew
  # Caso queira que isso não apareça, marque Debug como false.
  Debug: true
  #
  # Pegue sua KEY API aqui: https://painel.lojasquare.net/pages/conta/dados (ABA: SEGURANÇA)
  # KEY-API Aqui
  KEY_API: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  # Pegue sua SECRET API aqui: https://painel.lojasquare.net/pages/conta/dados (ABA: SEGURANÇA)
  # SECRET_KEY Aqui
  SECRET_KEY: "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  # Nome do servidor cadastrado aqui: https://painel.lojasquare.net/pages/pacotes/servidores
  Servidor: "Nome-Do-Servidor"
  Token_Servidor: "BBBBBBBBBBBBBBBBBBBB"
  # Tempo que o plugin tentará se conectar com o site.
  Connection_Timeout: 10000
  Read_Timeout: 10000

Config:
  # Permissao para usar este comando: lojasquare.qrcode.usar
  Cmd_Abrir_Menu_GUI: "/pix"
  # Ao fechar o inventario, percorrer item por item e checar se este item é do menu GUI
  # Se for do menu GUI, remover o item do inventario.
  # Evita de o player sair com algum item do inventario (menu).
  Fechar_Inv_Checar_Se_Tem_Item_Indevido: true
  Anuncio:
    Ativar: true
    # Tempo em segundos
    Tempo_Repetir_Anuncio: 60
    Mensagem:
      - '&b '
      - '&bQuer comprar sem sair do jogo?'
      - '&bDigite agora: &a/pix'
      - '&bEscolha o que quer receber &eIN-GAME.'
      - '&bEscolha a &aquantidade.'
      - '&bGere o &3QrCode'
      - '&bPague o &3QrCode'
      - '&bE &d&lRECEBA!'
      - '&bRapido, pratico e objetivo!'
      - '&b'
  HTTPS: true

GUI:
  Principal:
    # Em slots, o "bau" tem no minimo 9 slots.
    # Se quiser 3 linhas com 9 slots cada, coloque 27.
    # Sempre valores multiplos de 9.
    Tamanho: 9
    Nome: "&6PIX &bIn-Game"
    Completar_GUI: true
    Item_ID_Completar_GUI: "20:0"
  Confirmar:
    # Em slots, o "bau" tem no minimo 9 slots.
    # Se quiser 3 linhas com 9 slots cada, coloque 27.
    # Sempre valores multiplos de 9.
    Tamanho: 18
    Nome: "&6Confirmar Pedido"
    Completar_GUI: true
    Item_ID_Completar_GUI: "20:0"
    Item_Escolhido_Compra:
      Linha: 1
      Slot: 5
    Item_Confirmar_GerarQrcode:
      Linha: 2
      Slot: 9
      ID: "41:0"
      Nome: "&6CONFIRMAR"
      Lore:
        - '&eClique aqui para gerar o QrCode.'
    Item_Voltar_Menu_Principal:
      Linha: 2
      Slot: 1
      ID: "4:0"
      Nome: "&cCANCELAR"
      Lore:
        - '&cClique aqui para voltar ao menu anterior.'
    Item_Aumentar_Quantidade:
      Linha: 1
      Slot: 6
      ID: "262:0"
      Nome: "&eAumentar"
      Lore:
        - '&eClique aqui para aumentar a quantidade.'
        - '&eAdicao: &a+1 &eunidade'
    Item_Diminuir_Quantidade:
      Linha: 1
      Slot: 4
      ID: "262:0"
      Nome: "&cDiminuir"
      Lore:
        - '&cClique aqui para diminuir a quantidade.'
        - '&cReducao: &a-1 &cunidade'

Mapa:
  Msg_Ao_Gerar: "&3[LsQrCode] &bQrCode gerado com sucesso!"
  Item:
    Nome: "&6Doacao"
    Lore:
      - '&ePara completar a doacao'
      - '&e1) Pegue seu celular'
      - '&e2) Abra o App do banco'
      - '&e3) Va na area do PIX'
      - '&e4) Escaneie o QrCode'
      - '&e5) Realize o pagamento'
      - '&e6) Voce recebera os brindes in-game &aAUTOMATICAMENTE&e!!'

Msg:
  Sem_Permissao: "&cVoce nao tem permissao para executar este comando."
  Remova_O_Item_Da_Mao: "&cVoce nao deve ter nenhum item na mao para executar este comando."
  Falha_Gerar_Qrcode: "&cHouve uma falha ao gerar o QrCode. Erro: &a@erro"
  Nao_Foi_Possivel_Identificar_Produto_Selecionado: "&cOps... Nao identificamos o produto selecionado. Voce pode tentar novamente agora."
  Aguarde_Delay: "&cAguarde &a@tempo segundo(s)&c para executar essa acao novamente."
  Aguarde_Gerando_QrCode: "&eAguarde... Estamos gerando seu QrCode."
  Use_Cmd_Pix: "&eUse: &a/pix &agerar <&7Grupo&a/&7Id Produto&a> <&7Quantidade&a>"
  Use_Numeros_No_Campo_IdProduto_Quantidade: "&cUse numeros no campo Id Produto e Quantidade. Ex.: &a/pix 1234 1"
