#######################################################################################
#                                                                                     #
# ██╗      ██████╗      ██╗ █████╗ ███████╗ ██████╗ ██╗   ██╗ █████╗ ██████╗ ███████╗ #
# ██║     ██╔═══██╗     ██║██╔══██╗██╔════╝██╔═══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ #
# ██║     ██║   ██║     ██║███████║███████╗██║   ██║██║   ██║███████║██████╔╝█████╗   #
# ██║     ██║   ██║██   ██║██╔══██║╚════██║██║▄▄ ██║██║   ██║██╔══██║██╔══██╗██╔══╝   #
# ███████╗╚██████╔╝╚█████╔╝██║  ██║███████║╚██████╔╝╚██████╔╝██║  ██║██║  ██║███████╗ #
# ╚══════╝ ╚═════╝  ╚════╝ ╚═╝  ╚═╝╚══════╝ ╚══▀▀═╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ #
#                                                                                     #
#######################################################################################
#

LojaSquare:
  # Essa opção irá imprimir uma mensagem de status para quem é op.
  # Exemplo da impressão: https://prnt.sc/smvuew
  # Caso queira que isso não apareça, marque Debug como false.
  Debug: true
  # A opcao Smart_Delivery funciona da seguinte forma:
  # Se o Smart_Delivery estiver marcado como true, e um player comprar 10 Vips no site. Ao inves de o plugin executar 10x o
  # comando que voce colocou, sera executado apenas 1x com a quantidade 10 embutida no placeholder @qnt
  # (@qnt fica la nos comandos dos grupos, ali em baixo).
  # Ou seja, o plugin sera inteligente e executara menos comandos, realizando a entrega e trazendo um melhor desempenho.
  # Se o Smart_Delivery estiver marcado como false, o plugin ira executar 10x o comando que voce colocou
  # (ou a quantidade de vezes que o player comprou). Entao se voce tiver pacote de cash e o player comprar 500 pacotes de cash, o
  # plugin ira executar 500x os comandos de entrega do cash.
  # Ai vai depender de como voce prefere a entrega. Recomendamos deixar true.
  Smart_Delivery: true
  # Nome do servidor cadastrado aqui: https://painel.lojasquare.net/pages/pacotes/servidores
  Servidor: "Nome-Do-Servidor"
  # Tempo que o plugin tentará se conectar com o site.
  Connection_Timeout: 10000
  Read_Timeout: 10000

SQL:
  # Dados do banco de dados parametrizado no Bot de Busca-Pedidos da LojaSquare
  # O Bot de Busca-Pedidos, busca os pedidos pendentes na LojaSquare e os registra em uma base 'fria' (local) sua, para te dar maior controle as ativações.
  Host: "localhost"
  Database: "trow"
  User: "trow"
  Pass: "123"